<?php

/**
 * @file
 * Implementation of hook_node_view_alter();
 */

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function product_node_view(array &$build, \Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display, $view_mode) {

  $build['mybutton'] = [
    '#type'       => 'button',
    '#name'       => 'mybutton_name',
    '#value'      => t('Click Here'),

  ];
  
}